### ISSUE TITLE
Multiple ConfigureServices is not supported

### ISSUE THREAD

**Issue by awyl** [ivaylokenov/MyTested.AspNetCore.Mvc#270]
I have an aspnet core mvc project that uses DryIoc as the dependency container.  When I add a teststartup class with ConfigureServices, the framework returns this exception.

>The type initializer for 'MyTested.AspNetCore.Mvc.MyController`1' threw an exception.
Having multiple overloads of method 'ConfigureServices' is not supported.

This is the method:
`        public IServiceProvider ConfigureServices(IServiceCollection services) {
            return base.ConfigureServices( services );
        }
`

Sorry if I missed the documentation, I could not find anything specified for using 3rd party DI.  How should I setup?

Thanks!

**Comment by ivaylokenov** [comment]
@awyl Without a sample code, I am going to make a wild guess. Can you try renaming the method to `ConfigureTestServices`?

**Comment by awyl** [comment]
That did not work. I have attached a sample project to reproduce the issue.  Run the test, you will see the exception I mention above.  

Thanks!  Hope this can help you fix the issue.

[sample.zip](https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/files/787600/sample.zip)

**Comment by ivaylokenov** [comment]
@awyl Thank you. I will take a look and upload a version with a fix by the end of the week.

**Comment by awyl** [comment]
@ivaylokenov Any updates?  Thanks!

**Comment by ivaylokenov** [comment]
@awyl Hi, I found the ASP.NET Core guys added a `ConfigureContainer` method to the `Startup` file from 1.1: https://github.com/davidfowl/ServiceProviderFactorySample

I have missed this new feature, so I am currently working on supporting it out of the box. Will release a new version as soon as it is ready.

I am sorry for the inconvenience caused and thank you for your patience!

**Comment by awyl** [comment]
Thanks!!

**Comment by ivaylokenov** [comment]
@awyl FYI: I am almost ready with the implementation but will wait for Visual Studio 2017 to port the project to the new MSBuild system/.NET Core/ASP.NET Core in order to release the new packages at once and not make two releases in the timespan of just a few days.

**Comment by awyl** [comment]
Hi @ivaylokenov, any updates on this issue?  Thanks!

**Comment by ivaylokenov** [comment]
@awyl I am having trouble migrating the projects to the new MSBuild format. Will let you know, once I have finished this task. Thank you for your patience. 👍

**Comment by ppumkin** [comment]
Is this issue still open? I seem to be having a problem that is bringing me to this ticket.

**Comment by Felixking** [comment]
Any updates on this? Running into same issue.

**Comment by ppumkin** [comment]
I dropped down to core 2.0 it works for now

**Comment by ivaylokenov** [comment]
@awyl @ppumkin @Levitikon217 

Hi guys,

The library is now ported to .NET Core 2 and this feature is now implemented. You may take a look at https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/tree/development/samples/Autofac. The sample uses AutoFac but the principle should be the same. I will provide a sample with DryIoc and will leave this issue open for now.

I will try to explain why it was delayed by so much time.

Back in March 2017 when .NET Core migrated to the new (old) .csproj file format, I was having difficulties with the project as it can be seen here - #270 (comment)

Visual Studio was continually crashing, tests did not run correctly, and the overall developing experience was terrible. I tried for 2-3 months to port the library but could not succeed.

During that time, I started developing severe health issues from staying in front of my computer too much. I was working 12 to 16 hours from Monday to Sunday with not many breaks for 2-3 years straight. I had to stop doing it for an indefinite time. My GitHub activity shows this pretty clearly: https://github.com/ivaylokenov

The truth is - I like this testing library and have much fun developing it, so I was confused and did not know what to tell people about its future maintenance. I did not want to abandon it forever but did not know when I would be able to work actively again on it. I now realize that it was a mistake to be silent all this time and should have put an explanation earlier. The fact that my personal life was very stressful for the last two years is not an excuse.

Back in October 2018, I opened the code and started working actively on bringing back the library to life. It took me 6 months because I added lots of new features like third-party DI support, all possible action results, every single action filter, lots of helper methods for easier testing, more straightforward configuration, performance fixes and more. Version 2.2 is available on NuGet already, and version 2.1 will be published in the next few days. I will then update the tutorial, documentation, the web site, and will start working on .NET Core 3.

I am sorry for the inconvenience caused by this library and me. I truly am.

As compensation (if that is even possible), all versions before 3.0 do not have any limitations and can be used without any license code.

The good news is that I found a small private investor who is sponsoring the project. I can actively put 20 to 30 hours per week in the development of MyTested.AspNetCore.Mvc. If I manage to increase the usage and find clients, the investor will increase the budget and I will be able to hire another developer to help me. Additionally, I will put a sponsorship program with logos, and hopefully, I will be able to maintain the project steadily in the years to come.

Thank you for reading and understanding.

Ivaylo

Thank you for reading and understanding.

Ivaylo

**Comment by ppumkin** [comment]
Hey no problem. Hope you feeling better man. Health is first on list. I used to do what you did ... yea. Not healthy. Try some light jogging or walking. It really helps the blood flow and makes you feel alive.
Good luck with the project going forward. Stay healthy and thanks for everything

________________________________

**Comment by ivaylokenov** [comment]
@ppumkin Thank you for the understanding! I did exactly that - 1-2 hours a day doing sports. Feeling productive and great. Good luck to you too! 👌
