### ISSUE TITLE
Using with StructureMap IoC

### ISSUE THREAD

**Issue by thisispaulsmith** [ivaylokenov/MyTested.AspNetCore.Mvc#272]
Are there any examples of using MyTested with StructureMap?

As StrutureMap is configured via the `WebHostBuilder` this causes an issue

```
The type initializer for 'MyTested.AspNetCore.Mvc.MyMvc' threw an exception.
No service for type 'Microsoft.Extensions.DependencyInjection.IServiceProviderFactory`1[StructureMap.Registry]' has been registered.
```

**Comment by ivaylokenov** [comment]
Hi @thisispaulsmith,

The library is now ported to .NET Core 2 and this feature is now implemented. You may take a look at https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/tree/development/samples/Autofac. The sample uses AutoFac but the principle should be the same. I will provide a sample with StructureMap and will leave this issue open for now.

 I will try to explain why it was delayed by so much time.

Back in March 2017 when .NET Core migrated to the new (old) .csproj file format, I was having difficulties with the project as it can be seen here - #270 (comment)

Visual Studio was continually crashing, tests did not run correctly, and the overall developing experience was terrible. I tried for 2-3 months to port the library but could not succeed.

During that time, I started developing severe health issues from staying in front of my computer too much. I was working 12 to 16 hours from Monday to Sunday with not many breaks for 2-3 years straight. I had to stop doing it for an indefinite time. My GitHub activity shows this pretty clearly: https://github.com/ivaylokenov

The truth is - I like this testing library and have much fun developing it, so I was confused and did not know what to tell people about its future maintenance. I did not want to abandon it forever but did not know when I would be able to work actively again on it. I now realize that it was a mistake to be silent all this time and should have put an explanation earlier. The fact that my personal life was very stressful for the last two years is not an excuse.

Back in October 2018, I opened the code and started working actively on bringing back the library to life. It took me 6 months because I added lots of new features like third-party DI support, all possible action results, every single action filter, lots of helper methods for easier testing, more straightforward configuration, performance fixes and more. Version 2.2 is available on NuGet already, and version 2.1 will be published in the next few days. I will then update the tutorial, documentation, the web site, and will start working on .NET Core 3.

I am sorry for the inconvenience caused by this library and me. I truly am.

As compensation (if that is even possible), all versions before 3.0 do not have any limitations and can be used without any license code.

The good news is that I found a small private investor who is sponsoring the project. I can actively put 20 to 30 hours per week in the development of MyTested.AspNetCore.Mvc. If I manage to increase the usage and find clients, the investor will increase the budget and I will be able to hire another developer to help me. Additionally, I will put a sponsorship program with logos, and hopefully, I will be able to maintain the project steadily in the years to come.

Thank you for reading and understanding.

Ivaylo
