### ISSUE TITLE
Problem on resolving DbContext in a Domain-Driven Design Solution

### ISSUE THREAD

**Issue by HesamKashefi** [ivaylokenov/MyTested.AspNetCore.Mvc#276]
Hi, 
I've used Domain-Driven Design approach for My project so it has a main DbContext that has all the DbSets and some other DbContext for each BoundedContext of the project which have only a subset of DbSets and and obviously Models have only a subset of properties of the Main ones...(all contexts use the same database).
I've registered the main dbContext in Startup.cs with AddDbContext .... Method and the others are registered with AddScoped<....> .
The project works fine but when I use MyTested.AspNetCore.Mvc for testing it fails to resolve repositories that don't use the Main dbContext ...
with error  : 
_

> Message: Test method MyAPI.Controllers.Tests.CardBoxesControllerTests.GetCardBoxes threw exception: 
> MyTested.AspNetCore.Mvc.Exceptions.UnresolvedServicesException: CardBoxesController could not be instantiated because it contains no constructor taking no parameters.

_
So what is the problem? how can I fix this? 
And I just guess that this is it's problem! Maybe I'm wrong but from my standing point I can't get to any other conclusion...

**Comment by HesamKashefi** [comment]
I manged to move a little forward by doing this : 

`services
                .AddEntityFramework()
                .AddEntityFrameworkSqlServer()
                .AddDbContext<MainDbContext>(options =>
                {
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                })
                .AddDbContext<SecondDbContext>(options =>
                {
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                })
                .AddDbContext<ThirdContext>(options =>
                {
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                });`
but the problem is it is using the database not an InMemory one! 
if I remove the actual database or just change the connectionString for tests i'll get this error : 

> Cannot open database "MyWebService" requested by the login. The login failed.
Login failed for user 'DESKTOP-T45OJPV\Hesam'.

and one more thing please update tutorials for VisualStudio2017 cause there is no project.json any more
and it's in .csproj which is xml and different ...

**Comment by HesamKashefi** [comment]
I took a look at the source code of MyTested.AspNetCore.Mvc and I found out the problem lies in the MyTested.AspNetCore.Mvc.EntityFrameworkCore ServiceCollectionEntityFrameworkCoreExtensions class where in the ReplaceDbContext it just replaces the first DbContext by calling FirstOrDefault() and ignores all other contexts...

So please fix it , it seems to be simple .

**Comment by HesamKashefi** [comment]
Just a workaround for this problem : 
Add DbContexts to services this way : 
`.AddDbContext<DatabaseContext>(options =>
                {
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                })
                .AddDbContext<SecondDatabaseContext>(options =>
                {
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]);
                })`

Add this class to test project 
`using System;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using MyTested.AspNetCore.Mvc;
using MyTested.AspNetCore.Mvc.Internal;

namespace MyAPI.Controllers.Tests
{

    /// <summary>
    /// Contains Entity Framework Core extension methods for <see cref="IServiceCollection"/>.
    /// </summary>
    public static class ServiceCollectionEntityFrameworkCoreExtensions
    {
        private static readonly Type BaseDbContextType = typeof(DbContext);
        private static readonly Type BaseDbContextOptionsType = typeof(DbContextOptions);

        private static readonly MethodInfo ReplaceDatabaseMethodInfo =
            typeof(ServiceCollectionEntityFrameworkCoreExtensions)
                .GetTypeInfo()
                .GetDeclaredMethod(nameof(ReplaceDatabase));

        /// <summary>
        /// Replaces the registered <see cref="DbContext"/> with an in memory scoped implementation.
        /// </summary>
        /// <param name="serviceCollection">Instance of <see cref="IServiceCollection"/> type.</param>
        /// <returns>The same <see cref="IServiceCollection"/>.</returns>
        public static IServiceCollection ReplaceDbContext(this IServiceCollection serviceCollection)
        {
            var existingDbContextOptionsServices =
                serviceCollection.Where(s => BaseDbContextOptionsType.IsAssignableFrom(s.ServiceType)).ToList();

            foreach (var existingDbContextOptionsService in existingDbContextOptionsServices)
            {
                if (existingDbContextOptionsService != null)
                {
                    serviceCollection.Remove(existingDbContextOptionsService.ServiceType);
                }
            }

            var existingDbContexts =
                serviceCollection.Where(s => BaseDbContextType.IsAssignableFrom(s.ImplementationType)).ToList();

            if (existingDbContexts != null)
            {
                foreach (var existingDbContext in existingDbContexts)
                {
                    if (existingDbContext.Lifetime != ServiceLifetime.Scoped)
                    {
                        serviceCollection.Replace(
                            existingDbContext.ServiceType,
                            existingDbContext.ImplementationFactory,
                            ServiceLifetime.Scoped);
                    }
                    var genericMethod = ReplaceDatabaseMethodInfo.MakeGenericMethod(existingDbContext.ImplementationType);
                    genericMethod.Invoke(null, new object[] { serviceCollection });
                }

            }

            return serviceCollection;
        }

        private static void ReplaceDatabase<TDbContext>(IServiceCollection serviceCollection)
            where TDbContext : DbContext
        {
            serviceCollection.Replace<DbContext>(s => s.GetRequiredService<TDbContext>(), ServiceLifetime.Scoped);
            serviceCollection.AddDbContext<TDbContext>(opts =>
            {
                opts.UseInMemoryDatabase();

                ((IDbContextOptionsBuilderInfrastructure)opts).AddOrUpdateExtension(new ScopedInMemoryOptionsExtension());
            });
        }
    }
}`

This will be your Test Startup class
`public class TestStartup : Startup
    {
        public TestStartup(IHostingEnvironment env) : base(env)
        {
        }

        public void ConfigureTestServices(IServiceCollection services)
        {
            base.ConfigureServices(services);

            services.ReplaceDbContext();
            //services.Replace<IService, MockedService>();
        }
    }`

And that's it! now one more thing! you should sees Every one of the needed contexts in your Tests with the WithDbContext<YourDbContextType>(.....)
for example : 
` MyController<ItemsController>.Instance()
                .WithDbContext(dbContext => dbContext.WithEntities<DatabaseContext>(entities => entities.Add(...);))
.WithDbContext(dbContext => dbContext.WithEntities<SecondDatabaseContext>(entities =>entities.Add(...);))`

**Comment by ivaylokenov** [comment]
Hi @HesamKashefi,

The library is now ported to .NET Core 2 and this issue is now fixed. I will try to explain why it was delayed by so much time.

Back in March 2017 when .NET Core migrated to the new (old) .csproj file format, I was having difficulties with the project as it can be seen here - #270 (comment)

Visual Studio was continually crashing, tests did not run correctly, and the overall developing experience was terrible. I tried for 2-3 months to port the library but could not succeed.

During that time, I started developing severe health issues from staying in front of my computer too much. I was working 12 to 16 hours from Monday to Sunday with not many breaks for 2-3 years straight. I had to stop doing it for an indefinite time. My GitHub activity shows this pretty clearly: https://github.com/ivaylokenov

The truth is - I like this testing library and have much fun developing it, so I was confused and did not know what to tell people about its future maintenance. I did not want to abandon it forever but did not know when I would be able to work actively again on it. I now realize that it was a mistake to be silent all this time and should have put an explanation earlier. The fact that my personal life was very stressful for the last two years is not an excuse.

Back in October 2018, I opened the code and started working actively on bringing back the library to life. It took me 6 months because I added lots of new features like third-party DI support, all possible action results, every single action filter, lots of helper methods for easier testing, more straightforward configuration, performance fixes and more. Version 2.2 is available on NuGet already, and version 2.1 will be published in the next few days. I will then update the tutorial, documentation, the web site, and will start working on .NET Core 3.

I am sorry for the inconvenience caused by this library and me. I truly am.

As compensation (if that is even possible), all versions before 3.0 do not have any limitations and can be used without any license code.

The good news is that I found a small private investor who is sponsoring the project. I can actively put 20 to 30 hours per week in the development of MyTested.AspNetCore.Mvc. If I manage to increase the usage and find clients, the investor will increase the budget and I will be able to hire another developer to help me. Additionally, I will put a sponsorship program with logos, and hopefully, I will be able to maintain the project steadily in the years to come.

Thank you for reading and understanding.

Ivaylo

**Comment by HesamKashefi** [comment]
Hi @ivaylokenov 

I'm happy that you finally came back.

At first, I thought you have abandoned programming but after some time I realized there must be something strange going on ... cause I tried to find anywhere that I could search (Github, Instagram, Facebook, Email, Web site, ...).
I think I may get into the same trouble soon :) cause I'm doing 16 hours per day about 7 years (and we have only one day off per week here)! and I'm still hoping for a break! (programming is not a well-paid job in my country, our income is about 400$ per month, so we have to work  much more than other countries 😁).

I like this library and I tried to upgrade it for new versions of asp.net core many times but I could not do it, I could not even open the project easily because of my low-end Tablet PC which could not open a solution containing 80 projects easily let alone building it!

There is nothing to be sorry about, I understand what open source means and no one should be blamed for this.

I was following your commits and I was happy to see that it's happening.
I will try to let people around me about this library to increase its usage as I did before.

Thanks a lot for letting me know about what had happened and I wish you success.

Best regards.
Hesam Kashefi

**Comment by ivaylokenov** [comment]
@HesamKashefi Thank you very much for the kind words and your desire to help! Truly appreciate it! 

This is my Instagram, in case you need it: https://www.instagram.com/ivaylokenov/?hl=bg

Otherwise, try some sport. It really helps with staying a lot of time in front of a computer! :)
