### ISSUE TITLE
Fluent validations on model class

### ISSUE THREAD

**Issue by gkfischer** [ivaylokenov/MyTested.AspNetCore.Mvc#372]
All my validations on model classes are defined as fluent validations in OnModelCreating of the DataContext and not as attributes on the properties of the models, like so:
``` c#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
          modelBuilder.ApplyConfiguration(new ServiceConfiguration());
    }
```
``` c#
    public class ServiceConfiguration : IEntityTypeConfiguration<Service>
    {
        public void Configure(EntityTypeBuilder<Service> builder)
        {
            builder
                .Property(b => b.Name).IsRequired().HasMaxLength(250);
            builder
                .Property(b => b.ProductOwner).IsRequired().HasMaxLength(250);
            ...
        }
    }
```
But these validation rules are not loaded as it seems when the test framework runs as the ModelState collection doesn't contain any entries. How can I get the framework to load them?

**Comment by ivaylokenov** [comment]
These are database configurations, and not fluent validations. Does your web application register them in the ModelState, when you try to make a normal web request?

**Comment by gkfischer** [comment]
Nothing special done to register them, it's just an alternative way to specify restrictions on properties, like described here: https://docs.microsoft.com/en-us/ef/core/modeling/. When running the app these are added as validations to the ModelState.

**Comment by ivaylokenov** [comment]
I will take a look. Maybe it is some sort of misconfiguration on the library's end.

**Comment by gkfischer** [comment]
Thanks

**Comment by ivaylokenov** [comment]
I am not quite sure about this because I tried to reproduce it and the ModelState does not consider the IEntityTypeConfiguration fluent validation as I expected and it stays valid. These interface and configuration are database related. If you ModelState shows errors, you are configuring validation from somewhere else. I am attaching a solution, in which I am trying to reproduce your issue but cannot. Could you send me a solution sample of some sort so that I can take a look?

[TestFluentValidation.zip](https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/files/4170229/TestFluentValidation.zip)

**Comment by gkfischer** [comment]
I can do that over the weekend. Time's running out today

**Comment by ivaylokenov** [comment]
@gkfischer No worries, I will leave the issue open. Waiting for your input and will assist you as soon as possible. Thank you!

**Comment by gkfischer** [comment]
Ok, to make a long story short: my mistake. The fluent validations are only used by EF but not by the MVC framework. Strange design, as the DataAnnotations on the properties are used by both. But anyway, everythings fine when adding something like https://docs.fluentvalidation.net/en/latest/index.html.
