### ISSUE TITLE
Generic repository actions not recognized by framework

### ISSUE THREAD

**Issue by gkfischer** [ivaylokenov/MyTested.AspNetCore.Mvc#375]
I'm using  a gerneric repository pattern in an application (a working sample is attached). When using the generic mehtods, the MyTestes framework doesn't detect the changes in the database.

Two actions can be called from the UI: AddCountry() and AddCountryContext(). These two add records to the database, so the code ist working as expected.

I also added two methods to the home controller AddCountry(Country country) and AddCountryContext(Country country) that are called from the tests and from the UI actions. When running the tests, the AddCountryContext(Country country) succeeds, where as the AddCountry(Country country), which is the one I want to use naturally, fails.

Thanks for any help.

[OrderingTest.zip](https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/files/4399537/OrderingTest.zip)

**Comment by ivaylokenov** [comment]
Hi, it is because of the following code:

```c#
public OrderManagerUnitOfWork()
        public OrderManagerUnitOfWork()
        {
            _context = new OrderManagerContext();
        }

        public OrderManagerUnitOfWork(DbContextOptions<OrderManagerContext> options, ILoggerFactory loggerFactory, IConfiguration configuration)
        {
            _context = new OrderManagerContext(options, loggerFactory);
        }
```

In your Unit of work, you are creating a new Database context, which is different than the one, registered in the service provider. If you inject the context into the Unit of Work - it starts working:

```c#
        public OrderManagerUnitOfWork(OrderManagerContext context)
        {
            _context = context;
        }
```

Here is the fixed sample:

[OrderingTest.zip](https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/files/4408367/OrderingTest.zip)

If this scenario fixes the problem, you may close the issue.

**Comment by gkfischer** [comment]
Thanks for figuring that out, that's  a pretty embarassing mistake.

**Comment by ivaylokenov** [comment]
No worries. Happens to everybody.
