### ISSUE TITLE
NullReferenceException on basic test scenario

### ISSUE THREAD

**Issue by stanislavstoyanov99** [ivaylokenov/MyTested.AspNetCore.Mvc#386]
I found out a bug when AddRazorRuntimeCompilation() is used on my original Startup.cs class in the ASP.NET Core web project.

I provide more information written as comment in a similar issue from April 2020 - #377:

@ivaylokenov I found out the same problem writing simple test case in order to see the work of the library. Thank you for the "hack", but it will be fine if this bug is solved in the next releases of the library. :)

P.P. @ivaylokenov After making the required changes in #377, I receive the same error: "Object reference not set to an instance of an object.".

_Originally posted by @stanislavstoyanov99 in https://github.com/ivaylokenov/MyTested.AspNetCore.Mvc/issues/377#issuecomment-753658769_

**Comment by ivaylokenov** [comment]
@stanislavstoyanov99 To provide you a fix and new version, I would need the following:

**Describe your issue**
A clear and concise description of what the bug is.

**Project files**
Please include your Web and Test projects' `.csproj` files.

**Startup classes**
Please include your Web and Test project's `Startup` and `TestStartup` classes.

**Expected behavior**
Add a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
